"""Phase 0B classifier: SURFACE / EVIDENCE / ARCHIVED / FALSE_POSITIVE."""
from __future__ import annotations

import os
import re
import sys
from pathlib import Path

FILES = Path("audit/_files.txt").read_text().splitlines()

EVIDENCE_NAME_RE = re.compile(
    r"(_report|_proof|_bundle|_numerical|_registry|_ledger|_hashes|"
    r"_manifest|_provenance|_analysis|_tests|_fit|_results|_summary|"
    r"^data_|^gamma_|^final_|^xform_|_ci\.json$|_runs\.json$)",
    re.IGNORECASE,
)

EVIDENCE_DIRS = (
    "results/",
    "evidence/",
    "substrates/kuramoto/results/",
    "substrates/kuramoto/data/",
    "substrates/mfn/results/",
    "substrates/mfn/data/",
    "substrates/mlsdm/results/",
    "substrates/mlsdm/data/",
    "substrates/bn_syn/results/",
    "substrates/bn_syn/data/",
    "substrates/levin_bridge/data/",
)

ARCHIVE_PATTERNS = (
    "/archive/",
    "/archived/",
    "_archive_",
    "SESSION_CLOSE_",
    "/old/",
    "/deprecated/",
)


def classify(p: str) -> str:
    lower = p.lower()
    # ARCHIVED
    for pat in ARCHIVE_PATTERNS:
        if pat.lower() in lower:
            return "ARCHIVED"
    # EVIDENCE dirs
    for d in EVIDENCE_DIRS:
        if p.startswith(d) or ("/" + d) in p:
            if p.endswith((".json", ".yaml", ".yml")):
                return "EVIDENCE"
            if p.endswith(".md") and ("INDEX" in p.upper() or "LEDGER" in p.upper()):
                return "EVIDENCE"
    # EVIDENCE by filename signature
    name = os.path.basename(p)
    if p.endswith(".json") and EVIDENCE_NAME_RE.search(name):
        return "EVIDENCE"
    # .yaml/.yml config/canon at top-level or docs: SURFACE; in evidence/: EVIDENCE
    if p.endswith((".yaml", ".yml")):
        if "evidence/" in p or "results/" in p or "data/" in p:
            return "EVIDENCE"
        return "SURFACE"
    # .json: default EVIDENCE
    if p.endswith(".json"):
        return "EVIDENCE"
    # .md, .tex default SURFACE
    if p.endswith((".md", ".tex")):
        return "SURFACE"
    return "FALSE_POSITIVE"


buckets: dict[str, list[str]] = {
    "SURFACE": [],
    "EVIDENCE": [],
    "ARCHIVED": [],
    "FALSE_POSITIVE": [],
}
for f in FILES:
    f = f.strip()
    if not f:
        continue
    buckets[classify(f)].append(f)

for k, v in buckets.items():
    v.sort()
    print(f"{k}: {len(v)}")

# Write surfaces.yaml
out = ["# Phase 0B · Surface inventory", "# generated by audit/_classify.py", ""]
for cls in ("SURFACE", "EVIDENCE", "ARCHIVED", "FALSE_POSITIVE"):
    out.append(f"{cls}:")
    if not buckets[cls]:
        out.append("  []")
        continue
    for f in buckets[cls]:
        out.append(f"  - {f}")
    out.append("")
Path("audit/surfaces.yaml").write_text("\n".join(out))

# Write current_claims.md for SURFACE-class only
scan_lines = Path("audit/pre_closure_scan.txt").read_text().splitlines()
by_file: dict[str, list[str]] = {}
for ln in scan_lines:
    if ":" not in ln:
        continue
    path, rest = ln.split(":", 1)
    by_file.setdefault(path, []).append(ln)

claim_out = [
    "# Phase 0B · Current claims per SURFACE",
    "",
    "Extracted verbatim lines mentioning γ/Kuramoto/universality/cost-complexity",
    "from every SURFACE-class file identified in surfaces.yaml.",
    "",
    f"Total SURFACE files: {len(buckets['SURFACE'])}",
    "",
]
for f in buckets["SURFACE"]:
    lines = by_file.get(f, [])
    claim_out.append(f"## {f}")
    claim_out.append("")
    claim_out.append(f"_matches: {len(lines)}_")
    claim_out.append("")
    claim_out.append("```")
    for ln in lines[:80]:  # cap at 80 lines/file for digestibility
        claim_out.append(ln)
    if len(lines) > 80:
        claim_out.append(f"... [{len(lines) - 80} more lines omitted; see audit/pre_closure_scan.txt]")
    claim_out.append("```")
    claim_out.append("")
Path("audit/current_claims.md").write_text("\n".join(claim_out))

# Canon-file flag
canon = [
    "# Phase 0B · Existing canon files (protected)",
    "",
    "These files exist in repo and are subject to special rules per patch v1.2:",
    "",
]
for target in ("docs/CLAIM_BOUNDARY.md", "docs/CLAIM_BOUNDARY_CNS_AI.md"):
    exists = Path(target).exists()
    canon.append(f"- `{target}` — {'EXISTS' if exists else 'MISSING'}")
Path("audit/canon_files.md").write_text("\n".join(canon) + "\n")

print("\nwrote: audit/surfaces.yaml, audit/current_claims.md, audit/canon_files.md")
