"""Centralized constants for the cortex service."""

from __future__ import annotations

# Signal computation constants
DEFAULT_RESCALE_MIN = -1.0
DEFAULT_RESCALE_MAX = 1.0
DEFAULT_SMOOTHING_FACTOR = 0.25
DEFAULT_VOLATILITY_FLOOR = 1e-6
ZERO_STD_THRESHOLD = 1e-12

# Risk assessment constants
DEFAULT_MAX_ABSOLUTE_EXPOSURE = 2.0
DEFAULT_VAR_CONFIDENCE = 0.95
DEFAULT_STRESS_SCENARIOS = (0.85, 0.5)
MIN_CONFIDENCE = 0.0
MAX_CONFIDENCE = 1.0

# Regime modulation constants
DEFAULT_REGIME_DECAY = 0.2
DEFAULT_MIN_VALENCE = -1.0
DEFAULT_MAX_VALENCE = 1.0
DEFAULT_CONFIDENCE_FLOOR = 0.1
REGIME_CONFIDENCE_THRESHOLD_INDETERMINATE = 0.25
REGIME_VALENCE_THRESHOLD_BULLISH = 0.5
REGIME_VALENCE_THRESHOLD_BEARISH = -0.5

# Database constants
DEFAULT_FETCH_LIMIT = 50
MAX_FETCH_LIMIT = 1000

# API constants
DEFAULT_FEATURE_WEIGHT = 1.0
MIN_WEIGHT = 0.0
MAX_EXPOSURE_LIMIT = 10.0

# Cache constants
REGIME_CACHE_TTL_SECONDS = 5

# Retry constants
MAX_RETRY_ATTEMPTS = 3
RETRY_INITIAL_DELAY = 0.1
RETRY_MAX_DELAY = 2.0
RETRY_BACKOFF_MULTIPLIER = 2.0

__all__ = [
    "DEFAULT_RESCALE_MIN",
    "DEFAULT_RESCALE_MAX",
    "DEFAULT_SMOOTHING_FACTOR",
    "DEFAULT_VOLATILITY_FLOOR",
    "ZERO_STD_THRESHOLD",
    "DEFAULT_MAX_ABSOLUTE_EXPOSURE",
    "DEFAULT_VAR_CONFIDENCE",
    "DEFAULT_STRESS_SCENARIOS",
    "MIN_CONFIDENCE",
    "MAX_CONFIDENCE",
    "DEFAULT_REGIME_DECAY",
    "DEFAULT_MIN_VALENCE",
    "DEFAULT_MAX_VALENCE",
    "DEFAULT_CONFIDENCE_FLOOR",
    "REGIME_CONFIDENCE_THRESHOLD_INDETERMINATE",
    "REGIME_VALENCE_THRESHOLD_BULLISH",
    "REGIME_VALENCE_THRESHOLD_BEARISH",
    "DEFAULT_FETCH_LIMIT",
    "MAX_FETCH_LIMIT",
    "DEFAULT_FEATURE_WEIGHT",
    "MIN_WEIGHT",
    "MAX_EXPOSURE_LIMIT",
    "REGIME_CACHE_TTL_SECONDS",
    "MAX_RETRY_ATTEMPTS",
    "RETRY_INITIAL_DELAY",
    "RETRY_MAX_DELAY",
    "RETRY_BACKOFF_MULTIPLIER",
]
