from __future__ import annotations

import json
import subprocess
from pathlib import Path

import pytest

from bnsyn.qa.readiness_contract import (
    CommandSpec,
    ReadinessCheck,
    ReadinessState,
    ReadinessStatus,
    SubprocessCommandRunner,
    TRUTH_MODEL_FINGERPRINT,
    compute_truth_model_fingerprint,
    check_entropy_gate,
    check_mutation_baseline,
    check_release_readiness_document_contract,
    check_status_document_contract,
)
from scripts import release_readiness

_STATUS_DOC = """# Project Status

## Machine-readable release readiness

The only machine-readable release readiness source of truth is the execution-backed
report generated by `python -m scripts.release_readiness` and serialized to
`artifacts/release_readiness.json`.

- blocked
- advisory
- ready
"""

_RELEASE_DOC = """# Release Readiness Protocol

## Single-command truth source

`python -m scripts.release_readiness`

The JSON report includes `truth_model_version`.

## Readiness states

- blocked
- advisory
- ready

`ready requires at least one execution-backed check`

## Subsystems

1. static quality
2. runtime proof path
3. bundle validation
4. governance consistency
"""


class _StubRunner:
    def __init__(
        self,
        exit_codes: dict[str, int],
        *,
        stdout_by_command: dict[str, str] | None = None,
        stderr_by_command: dict[str, str] | None = None,
    ) -> None:
        self.exit_codes = exit_codes
        self.stdout_by_command = stdout_by_command or {}
        self.stderr_by_command = stderr_by_command or {}
        self.commands: list[str] = []

    def run(self, spec, repo_root: Path):  # type: ignore[no-untyped-def]
        del repo_root
        self.commands.append(spec.command)
        return type(
            "Outcome",
            (),
            {
                "exit_code": self.exit_codes.get(spec.command, 0),
                "stdout": self.stdout_by_command.get(spec.command, f"stdout::{spec.command}"),
                "stderr": self.stderr_by_command.get(spec.command, ""),
                "duration_seconds": 0.25,
            },
        )()


def _write_governance_inputs(tmp_path: Path) -> None:
    docs_dir = tmp_path / "docs"
    docs_dir.mkdir()
    (docs_dir / "STATUS.md").write_text(_STATUS_DOC, encoding="utf-8")
    (docs_dir / "RELEASE_READINESS.md").write_text(_RELEASE_DOC, encoding="utf-8")
    quality_dir = tmp_path / "quality"
    quality_dir.mkdir()
    (quality_dir / "mutation_baseline.json").write_text(
        json.dumps({"status": "active", "metrics": {"total_mutants": 2, "killed_mutants": 1}}),
        encoding="utf-8",
    )
    entropy_dir = tmp_path / "entropy"
    entropy_dir.mkdir()
    (entropy_dir / "policy.json").write_text(
        json.dumps({"comparators": {"process.required_checks_files_present": "eq"}}),
        encoding="utf-8",
    )
    (entropy_dir / "baseline.json").write_text(
        json.dumps({"process": {"required_checks_files_present": True}}),
        encoding="utf-8",
    )
    (tmp_path / "pyproject.toml").write_text("[project]\nversion='1.2.3'\n", encoding="utf-8")


def test_check_mutation_baseline_rejects_trivial_baseline(tmp_path: Path) -> None:
    baseline_path = tmp_path / "mutation_baseline.json"
    baseline_path.write_text(
        json.dumps(
            {
                "status": "active",
                "metrics": {
                    "total_mutants": 10,
                    "killed_mutants": 0,
                },
            }
        ),
        encoding="utf-8",
    )

    result = check_mutation_baseline(baseline_path)

    assert result.status == "fail"
    assert result.blocking is True
    assert "killed_mutants" in result.details


def test_check_mutation_baseline_rejects_malformed_json(tmp_path: Path) -> None:
    baseline_path = tmp_path / "mutation_baseline.json"
    baseline_path.write_text("{broken-json", encoding="utf-8")

    result = check_mutation_baseline(baseline_path)

    assert result.status == "fail"
    assert "Unreadable mutation baseline" in result.details


def test_check_entropy_gate_passes_when_metrics_match(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    entropy_dir = tmp_path / "entropy"
    entropy_dir.mkdir(parents=True)
    (entropy_dir / "policy.json").write_text(
        json.dumps(
            {
                "comparators": {
                    "process.required_checks_files_present": "eq",
                    "process.gh_workflows_missing_job_timeout_count": "lte",
                }
            }
        ),
        encoding="utf-8",
    )
    (entropy_dir / "baseline.json").write_text(
        json.dumps(
            {
                "process": {
                    "required_checks_files_present": True,
                    "gh_workflows_missing_job_timeout_count": 5,
                }
            }
        ),
        encoding="utf-8",
    )

    monkeypatch.setattr(
        "bnsyn.qa.readiness_contract.compute_metrics",
        lambda _repo_root: {
            "process": {
                "required_checks_files_present": True,
                "gh_workflows_missing_job_timeout_count": 4,
            }
        },
    )

    result = check_entropy_gate(tmp_path)

    assert result.status == "pass"
    assert result.blocking is True


def test_check_entropy_gate_rejects_unreadable_json(tmp_path: Path) -> None:
    entropy_dir = tmp_path / "entropy"
    entropy_dir.mkdir(parents=True)
    (entropy_dir / "policy.json").write_text("{broken-json", encoding="utf-8")
    (entropy_dir / "baseline.json").write_text(
        json.dumps({"process": {"required_checks_files_present": True}}),
        encoding="utf-8",
    )

    result = check_entropy_gate(tmp_path)

    assert result.status == "fail"
    assert "Unreadable entropy inputs" in result.details


def test_status_document_contract_requires_semantic_section(tmp_path: Path) -> None:
    status_path = tmp_path / "STATUS.md"
    status_path.write_text(
        "blocked advisory ready\npython -m scripts.release_readiness\nartifacts/release_readiness.json\n",
        encoding="utf-8",
    )

    result = check_status_document_contract(status_path)

    assert result.status == "fail"
    assert "Machine-readable release readiness" in result.details


def test_release_readiness_document_contract_requires_structured_subsystems(tmp_path: Path) -> None:
    release_path = tmp_path / "RELEASE_READINESS.md"
    release_path.write_text(
        """# Release Readiness Protocol\n\n## Readiness states\n- blocked\n- advisory\n- ready\n""",
        encoding="utf-8",
    )

    result = check_release_readiness_document_contract(release_path)

    assert result.status == "fail"
    assert "Missing sections" in result.details


def test_subprocess_command_runner_fails_closed_on_os_error(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    runner = SubprocessCommandRunner()
    monkeypatch.setattr(
        subprocess,
        "run",
        lambda *args, **kwargs: (_ for _ in ()).throw(OSError("boom")),
    )

    outcome = runner.run(
        CommandSpec(name="demo", command="demo", argv=("demo",), timeout_seconds=1.0),
        tmp_path,
    )

    assert outcome.exit_code == 124
    assert "OS error" in outcome.stderr


def test_subprocess_command_runner_fails_closed_on_timeout(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    runner = SubprocessCommandRunner()

    def _raise_timeout(*args: object, **kwargs: object) -> None:
        raise subprocess.TimeoutExpired(cmd=["demo"], timeout=1.0, stderr="late stderr")

    monkeypatch.setattr(subprocess, "run", _raise_timeout)

    outcome = runner.run(
        CommandSpec(name="demo", command="demo", argv=("demo",), timeout_seconds=1.0),
        tmp_path,
    )

    assert outcome.exit_code == 124
    assert "Timeout after 1.0s" in outcome.stderr


def test_readiness_state_scrubs_sensitive_output(tmp_path: Path) -> None:
    _write_governance_inputs(tmp_path)

    monkeypatch = pytest.MonkeyPatch()
    monkeypatch.setattr(
        "bnsyn.qa.readiness_contract.compute_metrics",
        lambda _repo_root: {"process": {"required_checks_files_present": True}},
    )
    try:
        state = ReadinessState.evaluate(
            tmp_path,
            command_runner=_StubRunner(
                {command: 0 for command in (
                    "ruff check .",
                    "mypy src --strict --config-file pyproject.toml",
                    "pylint src/bnsyn",
                    "bnsyn run --profile canonical --plot --export-proof",
                    "bnsyn validate-bundle <artifact_dir>",
                )},
                stdout_by_command={
                    "ruff check .": (
                        "SECRET_TOKEN=abc12345\n"
                        "ghp_abcdefghijklmnopqrstuvwxyz1234567890\n"
                        f"{tmp_path.as_posix()}/secret/file.txt\n"
                    )
                },
            ),
            proof_output_dir=tmp_path / "artifacts" / "bundle",
        )
    finally:
        monkeypatch.undo()

    check = state.subsystems[0].checks[0]
    assert check.stdout_excerpt is not None
    assert "SECRET_TOKEN" not in check.stdout_excerpt
    assert "ghp_" not in check.stdout_excerpt
    assert tmp_path.as_posix() not in check.stdout_excerpt
    assert "[REDACTED]" in check.stdout_excerpt or "[REPO_ROOT]" in check.stdout_excerpt


def test_readiness_state_reports_signal_termination(tmp_path: Path) -> None:
    _write_governance_inputs(tmp_path)

    monkeypatch = pytest.MonkeyPatch()
    monkeypatch.setattr(
        "bnsyn.qa.readiness_contract.compute_metrics",
        lambda _repo_root: {"process": {"required_checks_files_present": True}},
    )
    try:
        state = ReadinessState.evaluate(
            tmp_path,
            command_runner=_StubRunner(
                {
                    "ruff check .": 0,
                    "mypy src --strict --config-file pyproject.toml": 0,
                    "pylint src/bnsyn": 0,
                    "bnsyn run --profile canonical --plot --export-proof": -9,
                    "bnsyn validate-bundle <artifact_dir>": 1,
                }
            ),
            proof_output_dir=tmp_path / "artifacts" / "bundle",
        )
    finally:
        monkeypatch.undo()

    runtime_check = state.subsystems[1].checks[0]
    assert runtime_check.status == "fail"
    assert "SIGKILL" in runtime_check.details


def test_truth_model_fingerprint_matches_versioned_contract() -> None:
    assert TRUTH_MODEL_FINGERPRINT == compute_truth_model_fingerprint()


def test_readiness_state_blocks_when_execution_backed_checks_fail(tmp_path: Path) -> None:
    _write_governance_inputs(tmp_path)

    monkeypatch = pytest.MonkeyPatch()
    monkeypatch.setattr(
        "bnsyn.qa.readiness_contract.compute_metrics",
        lambda _repo_root: {"process": {"required_checks_files_present": True}},
    )
    try:
        state = ReadinessState.evaluate(
            tmp_path,
            command_runner=_StubRunner(
                {
                    "ruff check .": 1,
                    "mypy src --strict --config-file pyproject.toml": 1,
                    "pylint src/bnsyn": 1,
                    "bnsyn run --profile canonical --plot --export-proof": 1,
                    "bnsyn validate-bundle <artifact_dir>": 1,
                }
            ),
            proof_output_dir=tmp_path / "artifacts" / "bundle",
        )
    finally:
        monkeypatch.undo()

    assert state.status.value == "blocked"
    assert state.release_ready is False
    assert state.execution_backed_pass_count == 0


def test_release_readiness_script_is_not_file_only_gate(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    fake_state = ReadinessState(
        truth_model_version="1.2.0",
        timestamp="2026-03-19T00:00:00Z",
        version="9.9.9",
        status=ReadinessStatus.BLOCKED,
        release_ready=False,
        execution_backed_pass_count=0,
        blocking_failures=("Runtime proof path: canonical proof run",),
        advisory_findings=(),
        subsystems=(
            type(
                "Subsystem",
                (),
                {
                    "key": "runtime_proof_path",
                    "label": "Runtime proof path",
                    "status": ReadinessStatus.BLOCKED,
                    "checks": (
                        ReadinessCheck(
                            name="canonical proof run",
                            kind="command",
                            status="fail",
                            blocking=True,
                            details="Command failed",
                            command="bnsyn run --profile canonical --plot --export-proof",
                        ),
                    ),
                },
            )(),
        ),
    )

    monkeypatch.setattr(release_readiness.ReadinessState, "evaluate", lambda repo_root: fake_state)

    report = release_readiness.build_report(tmp_path)

    assert report["state"] == "blocked"
    assert report["release_ready"] is False
    assert report["execution_backed_pass_count"] == 0
    assert report["blocking_failures"]
