apiVersion: v1
kind: Service
metadata:
  name: logstash
  labels:
    app.kubernetes.io/name: logstash
    app.kubernetes.io/part-of: tradepulse
spec:
  selector:
    app.kubernetes.io/name: logstash
  ports:
    - name: beats
      port: 5044
      targetPort: beats
    - name: monitoring
      port: 9600
      targetPort: monitoring
