"""Compare performance metrics between the PR branch and ``main``.

The script reads benchmark JSON payloads generated by ``pytest-benchmark`` and
resource metrics collected by ``run_resource_checks.py``. It computes deltas,
produces human-readable summaries, and exits with a non-zero status if any
metric regresses beyond the configured threshold.

Exit codes:
    0: Success, no regressions detected
    1: Performance regression detected beyond allowed threshold
    2: Input validation error (missing/empty/invalid files)
"""

from __future__ import annotations

import argparse
import json
import math
import sys
import traceback
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable

BenchmarkMap = dict[str, "BenchmarkResult"]
ResourceMap = dict[str, "ResourceMetric"]


@dataclass(slots=True)
class BenchmarkResult:
    """Container for a single pytest-benchmark measurement."""

    name: str
    display_name: str
    median: float
    mean: float
    ops: float


@dataclass(slots=True)
class ResourceMetric:
    """Container for resource measurements generated by the collector."""

    name: str
    category: str
    value: float
    unit: str
    budget: float | None


@dataclass(slots=True)
class Comparison:
    """Computed delta between baseline and current measurements."""

    name: str
    unit: str
    baseline: float
    current: float
    delta_pct: float
    status: str
    extra: dict[str, Any]


@dataclass(slots=True)
class BenchmarkComparison(Comparison):
    ops_delta_pct: float | None = None


@dataclass(slots=True)
class ResourceComparison(Comparison):
    category: str = ""
    budget: float | None = None


_BENCHMARK_LABELS = {
    "tests/performance/test_indicator_benchmarks.py::test_compute_phase_hot_path": "kuramoto.compute_phase[128k]",
    "tests/performance/test_indicator_benchmarks.py::test_kuramoto_order_matrix": "kuramoto.order[4096x12]",
    "tests/performance/test_indicator_benchmarks.py::test_hierarchical_feature_stack": "hierarchical.features[3x2048]",
}


def _load_benchmarks(path: Path) -> BenchmarkMap:
    """Load benchmark results from pytest-benchmark JSON output.

    Args:
        path: Path to the benchmark JSON file.

    Returns:
        Dictionary mapping benchmark names to their results.

    Raises:
        ValueError: If the file is empty or contains invalid JSON.
    """
    text = path.read_text(encoding="utf-8")
    if not text.strip():
        raise ValueError(f"Empty benchmark file: {path}")
    try:
        data = json.loads(text)
    except json.JSONDecodeError as exc:
        raise ValueError(f"Invalid JSON in {path}: {exc}") from exc

    results: BenchmarkMap = {}
    for entry in data.get("benchmarks", []):
        fullname = entry.get("fullname") or entry.get("name")
        if not fullname:
            continue
        stats = entry.get("stats", {})
        display = _BENCHMARK_LABELS.get(fullname, entry.get("name", fullname))
        results[fullname] = BenchmarkResult(
            name=fullname,
            display_name=display,
            median=float(stats.get("median", math.nan)),
            mean=float(stats.get("mean", math.nan)),
            ops=float(stats.get("ops", math.nan)),
        )
    return results


def _load_resources(path: Path) -> ResourceMap:
    """Load resource metrics from the resource collector JSON output.

    Args:
        path: Path to the resource metrics JSON file.

    Returns:
        Dictionary mapping metric names to their values.

    Raises:
        ValueError: If the file is empty or contains invalid JSON.
    """
    text = path.read_text(encoding="utf-8")
    if not text.strip():
        raise ValueError(f"Empty resource file: {path}")
    try:
        data = json.loads(text)
    except json.JSONDecodeError as exc:
        raise ValueError(f"Invalid JSON in {path}: {exc}") from exc

    metrics: ResourceMap = {}
    for entry in data.get("metrics", []):
        name = entry.get("name")
        if not name:
            continue
        metrics[name] = ResourceMetric(
            name=name,
            category=str(entry.get("category", "unknown")),
            value=float(entry.get("value", math.nan)),
            unit=str(entry.get("unit", "")),
            budget=(
                float(entry["budget"])
                if "budget" in entry and entry["budget"] is not None
                else None
            ),
        )
    return metrics


def _ratio(new: float, baseline: float) -> float:
    if math.isnan(new) or math.isnan(baseline):
        return math.nan
    if baseline == 0:
        return math.inf if new > 0 else 1.0
    return new / baseline


def _format_delta(delta_pct: float) -> str:
    if math.isnan(delta_pct):
        return "n/a"
    sign = "+" if delta_pct >= 0 else ""
    return f"{sign}{delta_pct:.1f}%"


def _compare_benchmarks(
    baseline: BenchmarkMap,
    current: BenchmarkMap,
    *,
    threshold: float,
) -> list[BenchmarkComparison]:
    comparisons: list[BenchmarkComparison] = []
    for name, base_result in baseline.items():
        current_result = current.get(name)
        if not current_result:
            continue

        ratio = _ratio(current_result.median, base_result.median)
        delta_pct = (ratio - 1.0) * 100 if not math.isnan(ratio) else math.nan
        ops_ratio = _ratio(current_result.ops, base_result.ops)
        ops_delta_pct = (ops_ratio - 1.0) * 100 if not math.isnan(ops_ratio) else None

        status = "pass"
        if not math.isnan(delta_pct) and delta_pct > threshold * 100:
            status = "fail"
        if (
            status == "pass"
            and ops_delta_pct is not None
            and not math.isnan(ops_delta_pct)
            and ops_delta_pct < -threshold * 100
        ):
            status = "fail"

        comparisons.append(
            BenchmarkComparison(
                name=base_result.display_name,
                unit="seconds",
                baseline=base_result.median,
                current=current_result.median,
                delta_pct=delta_pct,
                status=status,
                extra={
                    "mean_baseline": base_result.mean,
                    "mean_current": current_result.mean,
                },
                ops_delta_pct=ops_delta_pct,
            )
        )
    return comparisons


def _compare_resources(
    baseline: ResourceMap,
    current: ResourceMap,
    *,
    threshold: float,
) -> list[ResourceComparison]:
    comparisons: list[ResourceComparison] = []
    for name, base_metric in baseline.items():
        current_metric = current.get(name)
        if not current_metric:
            continue

        ratio = _ratio(current_metric.value, base_metric.value)
        delta_pct = (ratio - 1.0) * 100 if not math.isnan(ratio) else math.nan
        status = "pass"
        if not math.isnan(delta_pct) and delta_pct > threshold * 100:
            status = "fail"
        if status == "fail" and current_metric.budget is not None:
            abs_delta = abs(current_metric.value - base_metric.value)
            abs_tolerance = max(0.05, current_metric.budget * 0.05)
            if current_metric.value <= current_metric.budget and abs_delta <= abs_tolerance:
                status = "pass"
        comparisons.append(
            ResourceComparison(
                name=name,
                unit=current_metric.unit,
                baseline=base_metric.value,
                current=current_metric.value,
                delta_pct=delta_pct,
                status=status,
                extra={},
                category=current_metric.category,
                budget=current_metric.budget,
            )
        )
    return comparisons


def _build_markdown(
    benchmarks: Iterable[BenchmarkComparison],
    resources: Iterable[ResourceComparison],
) -> str:
    lines: list[str] = []
    lines.append("### Benchmark comparison")
    lines.append("| Benchmark | Baseline (ms) | PR (ms) | Δ median | Δ OPS | Status |")
    lines.append("| --- | ---: | ---: | ---: | ---: | :---: |")
    for item in benchmarks:
        baseline_ms = item.baseline * 1000
        current_ms = item.current * 1000
        delta = _format_delta(item.delta_pct)
        ops_delta = (
            _format_delta(item.ops_delta_pct)
            if item.ops_delta_pct is not None
            else "n/a"
        )
        status_icon = "✅" if item.status == "pass" else "❌"
        lines.append(
            f"| {item.name} | {baseline_ms:.3f} | {current_ms:.3f} | {delta} | {ops_delta} | {status_icon} |"
        )

    lines.append("")
    lines.append("### Resource usage")
    lines.append("| Metric | Category | Baseline | PR | Δ | Budget | Status |")
    lines.append("| --- | --- | ---: | ---: | ---: | ---: | :---: |")
    for item in resources:
        if item.unit == "bytes":
            baseline_val = item.baseline / (1024**2)
            current_val = item.current / (1024**2)
            unit = "MiB"
            budget_display = (
                f"{item.budget / (1024 ** 2):.3f} {unit}"
                if item.budget is not None
                else "—"
            )
        else:
            baseline_val = item.baseline
            current_val = item.current
            unit = item.unit or ""
            budget_display = (
                f"{item.budget:.3f} {unit}".strip() if item.budget is not None else "—"
            )
        delta = _format_delta(item.delta_pct)
        status_icon = "✅" if item.status == "pass" else "❌"
        lines.append(
            f"| {item.name} | {item.category} | {baseline_val:.3f} {unit} | {current_val:.3f} {unit} | {delta} | {budget_display} | {status_icon} |"
        )
    lines.append("")
    return "\n".join(lines)


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--baseline-benchmark", type=Path, required=True)
    parser.add_argument("--current-benchmark", type=Path, required=True)
    parser.add_argument("--baseline-resources", type=Path, required=True)
    parser.add_argument("--current-resources", type=Path, required=True)
    parser.add_argument(
        "--threshold",
        type=float,
        default=0.20,
        help="Allowed slowdown ratio (e.g. 0.20 for 20%).",
    )
    parser.add_argument("--output-json", type=Path, required=True)
    parser.add_argument("--output-markdown", type=Path, required=True)
    return parser.parse_args()


def _validate_input_files(args: argparse.Namespace) -> None:
    """Validate that all input files exist and are non-empty.

    Args:
        args: Parsed command-line arguments.

    Raises:
        FileNotFoundError: If an input file does not exist.
        ValueError: If an input file is empty.
    """
    input_files = [
        args.baseline_benchmark,
        args.current_benchmark,
        args.baseline_resources,
        args.current_resources,
    ]
    for path in input_files:
        if not path.exists():
            raise FileNotFoundError(f"Missing input file: {path}")
        if path.stat().st_size == 0:
            raise ValueError(f"Empty file: {path}")


def main() -> None:
    """Main entry point for performance comparison.

    Exit codes:
        0: Success, no regressions detected
        1: Performance regression detected beyond allowed threshold
        2: Input validation error (missing/empty/invalid files)
    """
    args = _parse_args()

    try:
        # Validate input files before loading
        _validate_input_files(args)

        baseline_benchmarks = _load_benchmarks(args.baseline_benchmark)
        current_benchmarks = _load_benchmarks(args.current_benchmark)
        baseline_resources = _load_resources(args.baseline_resources)
        current_resources = _load_resources(args.current_resources)

    except (FileNotFoundError, ValueError) as exc:
        print(f"Input validation error: {exc}", file=sys.stderr)
        traceback.print_exc()
        sys.exit(2)
    except Exception:
        print("Unexpected error loading input files:", file=sys.stderr)
        traceback.print_exc()
        sys.exit(2)

    benchmark_results = _compare_benchmarks(
        baseline_benchmarks,
        current_benchmarks,
        threshold=args.threshold,
    )
    resource_results = _compare_resources(
        baseline_resources,
        current_resources,
        threshold=args.threshold,
    )

    markdown = _build_markdown(benchmark_results, resource_results)
    args.output_markdown.parent.mkdir(parents=True, exist_ok=True)
    args.output_markdown.write_text(markdown, encoding="utf-8")
    print(markdown)

    payload = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "threshold": args.threshold,
        "benchmarks": [
            {
                "name": item.name,
                "unit": item.unit,
                "baseline": item.baseline,
                "current": item.current,
                "delta_pct": item.delta_pct,
                "status": item.status,
                "mean_baseline": item.extra["mean_baseline"],
                "mean_current": item.extra["mean_current"],
                "ops_delta_pct": item.ops_delta_pct,
            }
            for item in benchmark_results
        ],
        "resources": [
            {
                "name": item.name,
                "category": item.category,
                "unit": item.unit,
                "baseline": item.baseline,
                "current": item.current,
                "delta_pct": item.delta_pct,
                "status": item.status,
                "budget": item.budget,
            }
            for item in resource_results
        ],
    }

    args.output_json.parent.mkdir(parents=True, exist_ok=True)
    args.output_json.write_text(
        json.dumps(payload, indent=2, sort_keys=True), encoding="utf-8"
    )

    failures = [item for item in benchmark_results if item.status == "fail"]
    failures.extend(item for item in resource_results if item.status == "fail")
    if failures:
        print(
            "Performance regression detected beyond allowed threshold",
            file=sys.stderr,
        )
        for f in failures:
            print(f"- {f.name} status={f.status} delta={f.delta_pct:.1f}%", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
