# Auto-generated by tools/schema/generate_event_types.py. DO NOT EDIT.
from __future__ import annotations

from enum import Enum
from typing import Dict, Optional

from pydantic import BaseModel, ConfigDict, Field


class FillLiquidity(Enum):
    MAKER = "MAKER"
    TAKER = "TAKER"


class FillStatus(Enum):
    PARTIAL = "PARTIAL"
    FILLED = "FILLED"
    CANCELLED = "CANCELLED"


class OrderSide(Enum):
    BUY = "BUY"
    SELL = "SELL"


class OrderType(Enum):
    MARKET = "MARKET"
    LIMIT = "LIMIT"
    STOP = "STOP"
    STOP_LIMIT = "STOP_LIMIT"


class SignalDirection(Enum):
    BUY = "BUY"
    SELL = "SELL"
    FLAT = "FLAT"


class TimeInForce(Enum):
    GTC = "GTC"
    DAY = "DAY"
    IOC = "IOC"
    FOK = "FOK"


class BarEvent(BaseModel):
    """Aggregated OHLCV bar for a symbol and interval."""

    model_config = ConfigDict(extra="forbid")
    event_id: str
    schema_version: str
    symbol: str
    timestamp: int
    interval: str
    open: float
    high: float
    low: float
    close: float
    volume: float
    vwap: Optional[float] = None
    trade_count: Optional[int] = None


class FillEvent(BaseModel):
    """Execution fill acknowledgment for an order."""

    model_config = ConfigDict(extra="forbid")
    event_id: str
    schema_version: str
    symbol: str
    timestamp: int
    order_id: str
    fill_id: str
    status: FillStatus
    filled_qty: float
    fill_price: float
    fees: Optional[float] = None
    liquidity: Optional[FillLiquidity] = None
    metadata: Dict[str, str] = Field(default_factory=dict)


class OrderEvent(BaseModel):
    """Order instruction emitted by the execution service."""

    model_config = ConfigDict(extra="forbid")
    event_id: str
    schema_version: str
    symbol: str
    timestamp: int
    order_id: str
    side: OrderSide
    order_type: OrderType
    quantity: float
    price: Optional[float] = None
    time_in_force: Optional[TimeInForce] = None
    routing: Optional[str] = None
    metadata: Dict[str, str] = Field(default_factory=dict)


class SignalEvent(BaseModel):
    """Generated trading signal with metadata and routing hints."""

    model_config = ConfigDict(extra="forbid")
    event_id: str
    schema_version: str
    symbol: str
    timestamp: int
    signal_type: str
    strength: float
    direction: SignalDirection
    ttl_seconds: Optional[int] = None
    metadata: Dict[str, str] = Field(default_factory=dict)


class TickEvent(BaseModel):
    """Real-time market tick update for a single symbol."""

    model_config = ConfigDict(extra="forbid")
    event_id: str
    schema_version: str
    symbol: str
    timestamp: int
    bid_price: float
    ask_price: float
    last_price: Optional[float] = None
    volume: Optional[int] = None
    microstructure: Optional[TickMicrostructure] = None


class TickMicrostructure(BaseModel):
    """Order book context captured alongside the tick."""

    model_config = ConfigDict(extra="forbid")
    bid_size: Optional[int] = None
    ask_size: Optional[int] = None
    trade_condition: Optional[str] = None
