"""Machine-checkable math contracts."""

from .math_contracts import (
    assert_adjacency_binary,
    assert_column_ranges,
    assert_coupling_matrix_properties,
    assert_dt_stability,
    assert_dtype_consistency,
    assert_energy_bounded,
    assert_integration_tolerance_consistency,
    assert_no_catastrophic_cancellation,
    assert_no_division_by_zero_risk,
    assert_no_duplicate_rows,
    assert_no_exp_overflow_risk,
    assert_no_log_domain_violation,
    assert_no_nan_in_dataset,
    assert_non_empty_text,
    assert_numeric_finite_and_bounded,
    assert_order_parameter_computation,
    assert_order_parameter_range,
    assert_phase_range,
    assert_phase_velocity_finite,
    assert_probability_normalization,
    assert_state_finite_after_step,
    assert_timeseries_monotonic_time,
    assert_weight_matrix_nonnegative,
)

__all__ = [
    "assert_adjacency_binary",
    "assert_column_ranges",
    "assert_coupling_matrix_properties",
    "assert_dt_stability",
    "assert_dtype_consistency",
    "assert_energy_bounded",
    "assert_integration_tolerance_consistency",
    "assert_no_catastrophic_cancellation",
    "assert_no_division_by_zero_risk",
    "assert_no_duplicate_rows",
    "assert_no_exp_overflow_risk",
    "assert_no_log_domain_violation",
    "assert_no_nan_in_dataset",
    "assert_non_empty_text",
    "assert_numeric_finite_and_bounded",
    "assert_order_parameter_computation",
    "assert_order_parameter_range",
    "assert_phase_range",
    "assert_phase_velocity_finite",
    "assert_probability_normalization",
    "assert_state_finite_after_step",
    "assert_timeseries_monotonic_time",
    "assert_weight_matrix_nonnegative",
]
